Fix exit if maestro isn't running

diff --git a/.github/workflows/unit_tests.yml b/.github/workflows/unit_tests.yml
--- a/.github/workflows/unit_tests.yml
+++ b/.github/workflows/unit_tests.yml
@@ -47,6 +47,10 @@ jobs:
           ./build/maestro &
           echo $! > /tmp/maestro_pid
           while ! nc -z localhost 8080; do
+            if ! ps -p `/tmp/maestro_pid` > /dev/null; then
+              echo "::error file=./build/maestro::Maestro exited unexpectedly"
+              exit 1
+            fi
             sleep 1
           done
         env:
